baseURL = 'https://openadmet.org/'
languageCode = 'en-us'
title = 'OpenADMET Test'
theme = 'kube'
description = "OpenADMET does blah blah blah"
publishDir = "./public"
pygmentsCodefences = true
pygmentsStyle = "colorful"

[Params]
  RSSLink = "/index.xml"
  author = "OpenADMET" # add your company name
  github = "https://github.com/OpenADMET" # add your github profile name
  twitter = "" # add your twitter profile
  email = "hugo.macdermott-opeskin@omsf.io"

[[menu.main]]
    name = "Members"
    weight = -170
    url = "/members/"
    identifier = "members"

[[menu.main]]
    name = "Blog"
    weight = 100
    url = "/blog/"
    identifier = "blog"


[[menu.main]]
    name = "Datasets and Models"
    weight = -150
    url = "/datasets_and_models/"
    identifier = "datasets_and_models"


[[menu.main]]
    name = "Publications"
    weight = -100
    url = "/publications/"
    identifier = "publications"

[[menu.main]]
    name = "Jobs"
    weight = -200
    url = "/jobs/"
    identifier = "jobs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
